---
title: 'Problem Set 2: Due Friday, July 2022, 11:59 PM'
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y, %H : %M : %S')`"
output:
  html_document:
    df_print: paged
---

**For these questions, use your project data set that you have chosen for the Project assignment or any test data set other than those used in class lectures or labs.**

**If you choose, you may also simulate a data set with at least 100 observations of at least two variables. If you do this, give the variables descriptive column names.**

1. What is the source of your data set? (Where did you get it?)

2. How did the source obtain the data? (Survey, experiment, observation/collection)

3. What are your two main variables of interest (x and y)?

4. How many observations are there?

**For either your x or y variable:**

5. What is the median?

6. What is the mean?

7. What are the sample variance and sample standard deviation?

8. What are the minimum and maximum?

9. What are the first and third quartiles?

10. Plot a histogram of the x variable.

Bonus - Do these for the other variable from your likely x and y (you will need to do this with two to four variables for the project). 

Code chunk below for your use:

```{r}

```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
