---
title: "Lab 9: Plotting Correlations, Scatterplots, and Histograms"
output: html_notebook
---

```{r}

# Loading a built in dataset with state information
my_data <- data.frame(state.x77)

#looking at the first 6 rows of the dataset
head(my_data)

```


+ Histograms

#Plot histograms of Population, Illiteracy, and Murder rates

**A simple histogram of population, no arguments to the function**

```{r}

#histogram of population
hist(my_data$Population)



```


**Histogram murder rates with some color and labels**

```{r, echo=FALSE}

#histogram of murder rates, color set by col = 
#main title set by main = , x-axis label set by
#xlab = 
hist(my_data$Murder, col = "red", main = "Histogram of State Murder Rates", xlab = "Murder Rate")


```

**Histogram of Illiteracy**

```{r, echo=FALSE}

hist(my_data$Illiteracy)

```




+ Scatterplots

                + Just the plot - illiteray vs murder
                
```{r, echo=FALSE}

#plotting illiteracy on the X-axis, Murder on the y-axis
#The pattern is (x,y) from geometry
#title is main = 
#xlab is x-axis label, ylab is y-axis label
plot(my_data$Illiteracy,my_data$Murder, main = "Plot of Illiteracy Rates vs Murder Rates", xlab = "Illiteracy Rate", ylab = "Murder Rate")

```

                
                + With means
                
```{r, echo=FALSE}

#plotting illiteracy on the X-axis, Murder on the y-axis
#The pattern is (x,y) from geometry
#title is main = 
#xlab is x-axis label, ylab is y-axis label
plot(my_data$Illiteracy,my_data$Murder, main = "Plot of Illiteracy Rates vs Murder Rates", xlab = "Illiteracy Rate", ylab = "Murder Rate")

#abline is the command to draw a line, v is a vertical line at the point given, I used the mean() function as the value
abline(v = mean(my_data$Illiteracy))

#abline with h is a horizontal line
abline(h = mean(my_data$Murder))

```
             
             
                + With smoothing
                
**Using the OLS linear model**

```{r, echo=FALSE}

#plotting illiteracy on the X-axis, Murder on the y-axis
#The pattern is (x,y) from geometry
#title is main = 
#xlab is x-axis label, ylab is y-axis label
plot(my_data$Illiteracy,my_data$Murder, main = "Plot of Illiteracy Rates vs Murder Rates", xlab = "Illiteracy Rate", ylab = "Murder Rate") 

#abline is the command for line     
#lm is the function for a linear regression 
#The Y variable goes before the ~ and the x variable after
abline(lm(my_data$Murder ~ my_data$Illiteracy))
```
   
                + Smoothing with the ggplot2 package  
                
```{r}
library(ggplot2)

#creating the ggplot as an object
#specify the dataframe with data =
#x = is the x variable, y = is the y variable
#geom_point() is for data plotted as points
#geom_smooth() tells it to add a smoothing line by the best
#available method
a <- ggplot(data = my_data, aes(x = Illiteracy, 
                                y = Murder)) + 
        geom_point() +
        geom_jitter() +
        geom_smooth()

#print a
a 
```


[ggplot2 vignettes](https://rpubs.com/sbellows1/589423)   
[ggplot2 Home page](https://ggplot2.tidyverse.org/)
                





