---
title: 'Lab 5: July 19'
author: 'POLS 3316, Summer 2022, University of Houston, Instructor: Tom Hanna'
output:
  html_document:
    df_print: paged
---

## Probability and set examples
**For some of these, you should just set up the problems, describe the sets, etc.**
**The code to make the symbols is:**

+ Union - $\cup$ : ````{verbatim} $\cup$ ````
+ Intercept - $\cap$ : ````{verbatim} $\cap $ ````
+ s complement - $s^c$ : ````{verbatim} $s^c $ ````
+ fractions $\frac{possible_A}{all \; possible \; outcomes}$ : ````{verbatim} $\frac{possible_A}{all \; possible \; outcomes}$ ````
+ fractions - $\frac{1}{2}$ : ```` $\frac{1}{2}$ ````
+ element - $\in$ : ````{verbatim} $\in$ ````
+ empty set - $\emptyset$ : ````{verbatim} $\emptyset$ ````

Examples:

1. Given the following fill in the blanks:

+ S = {5,10,15,20,25}
+ s = {5}
+ $s^c$ = {10,15,20,25}

2. Given the following fill in the blanks:

+ S = {HH,HT,TH,TT}
+ A = {HH}
+ $A^c$ = {HT,TH,TT}
+ P{A} = 1 event (HH) / 3 {HT, TH, TT}

3. Given the following fill in the blanks:

+ D = {A,B,C,D,E}
+ E = {D,E}
+ D $\cup$ E = {A,B,C,D,E}
+ D $\cap$ E = {D,E}

4. Given the following fill in the blanks:

S = {A,B,C,D,E,F,G,H}
+ A = {A}
+ B = {C,D,E}
+ P(A) = 1 / 8
+ P(B) = 3 / 8 
+ P(A $\cup$ B) = 1/8 + 3/8 = 4/8 = 1/2

5. What is the sample space for a coin toss? (Use H and T)

S = {H,T}

6. What is the sample space for a roll of a six sided die? (use numbers)

S = {1,2,3,4,5,6}

6a. Write a set B containing even rolls of a six sided die.

b = {2,4,6}

6b. Write a set A that is the complement of set B.

B = $b^c$ = {1,3,6}

6c. Are sets A and B mutually exclusive?

Yes

6d. What is the probability of an even roll (set B)?

P(B) = 3 favorable outcomes / 6 possibilities = 3/6 = 1/2 (or .5 or 50%)

6e. Using the probability of set B, what is the probability of its opposite (set A)? (In other words, do the math with the formula for finding A from its opposite, not just computing it directly.)

P(A) = 1 - P(B) = 1 - .5 = .5

7. What is the sample space for 2 rolls of a six sided die? (Show pairs like this 1-1,1-2, etc...)

S = {1-1,1-2,1-3,1-4,1-5,1-6,2-1,2-2,2-3,2-4,2-5,2-6,3-1,3-2,3-3,3-4,3-5,3-6,4-1,4-2,4-3,4-4,4-5,4-6,5-1,5-2,5-3,5-4,5-5,5-6,6-1,6-2,6-3,6-4,6-5,6-6}


7a. How many ways are there two get two sixes?

1

7b. How many ways are there to get a total of 9?

{4-5,5-4,3-6,6-3} : 4 ways

7c. How many ways are there to get a total of 4?

{3-1,1-3,2-2} : 3 ways

7d. How many elements are in the sample space?

36 (You can count them. You can also get this by multiplying 6 possibilities in the first roll times 6 possibilities in the second roll: 6 x 6 = 36)

7e. What is the probability of rolling a 4?

P(4) = 3 favorable outcomes / 36 possibilities = 3/36 = 1/12 or .08333 or 8.33%



